# frozen_string_literal: true

# Generated by forge 1.0.0 from CardPay Transfers API 2.3.0 (cardpay.yaml).
# Do not edit by hand: regenerate with `bin/forge generate`; adjust decisions in overrides.yml.

require 'base64'
require 'json'
require 'openssl'

module Provider
  class CardpayService < BaseService
    BASE_URL = ENV.fetch('CARDPAY_BASE_URL', 'https://api.cardpay.example/v2')

    STATUS_MAP = {
      'NEW'        => 'in_progress',
      'PROCESSING' => 'in_progress',
      'SUCCESS'    => 'approved',
      'DECLINED'   => 'rejected'
    }.freeze

    EVENT_MAP = {
      'transfer.settled'  => 'approved',
      'transfer.declined' => 'rejected'
    }.freeze

    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      403 => 'forbidden',
      404 => 'not_found',
      422 => 'validation_error',
      500 => 'internal_error',
      503 => 'unavailable'
    }.freeze

    SUCCESS_STATUSES = [201].freeze
    REQUISITE_TYPES = %w[card].freeze
    STATUS_METHODS = %w[status check].freeze
    SUPPORTED_CURRENCIES = %w[RUB USD].freeze
    SIGNATURE_HEADER = 'X-Signature'

    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?
      return failure(:unprocessable_entity, 'currency_not_supported') unless SUPPORTED_CURRENCIES.include?(operation.currency)
      return failure(:unprocessable_entity, 'reference_too_long') if operation.id.to_s.length > 40
      return failure(:unprocessable_entity, 'description_too_long') if (operation.description || "Payout #{operation.id}").to_s.length > 140
      return failure(:unprocessable_entity, 'requisite_missing') unless requisite_type_for(operation, request_method)

      pan = requisite_for(operation, 'card')['card_number']
      return failure(:unprocessable_entity, 'pan_invalid') if requisite_type_for(operation, request_method) == 'card' && !pan.to_s.match?(/\A\d{13,19}\z/)

      success
    end

    def create_request(operation, request_method = 'create')
      return fetch_status(operation) if STATUS_METHODS.include?(request_method)

      requisite_type = requisite_type_for(operation, request_method)
      return failure(:unprocessable_entity, 'requisite_missing') unless requisite_type

      payload = build_payout_payload(operation, requisite_type)
      response = client.post("#{BASE_URL}/transfers", json: payload, headers: auth_headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError => e
      failure(:too_many_requests, 'provider.rate_limit', retry_after: e.retry_after)
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    rescue Provider::ServerError, Provider::ConnectionError => e
      failure(:bad_gateway, 'provider.unavailable', message: e.message)
    end

    def fetch_status(operation)
      response = client.get("#{BASE_URL}/transfers/#{operation.provider_operation_key}", headers: auth_headers)
      return failure(http_symbol(response.status), "provider.#{error_code_for(response)}") unless response.status == 200

      apply_status(operation, response.body.dig('data', 'state'), strict: true)
    rescue Provider::RateLimitError => e
      failure(:too_many_requests, 'provider.rate_limit', retry_after: e.retry_after)
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    rescue Provider::ServerError, Provider::ConnectionError => e
      failure(:bad_gateway, 'provider.unavailable', message: e.message)
    end

    def process_callback(payload, raw_body: nil, headers: {})
      verify_signature!(raw_body || JSON.generate(payload), headers)
      internal_status = EVENT_MAP[payload['type']] || STATUS_MAP[payload.dig('data', 'state')]
      return failure(:unprocessable_entity, 'unknown_event', event: payload['type']) unless internal_status

      case internal_status
      when 'approved' then approve_operation(payload.dig('data', 'transfer_id'))
      when 'rejected' then reject_operation(payload.dig('data', 'transfer_id'), payload.dig('data', 'error', 'code'))
      else mark_in_progress(payload.dig('data', 'transfer_id'))
      end
    rescue Provider::SignatureError
      failure(:unauthorized, 'invalid_signature')
    end

    private

    def auth_headers
      { 'Authorization' => "Bearer #{credentials.fetch('token')}" }
    end

    def requisite_type_for(operation, request_method)
      return request_method if REQUISITE_TYPES.include?(request_method)

      (operation.payout_requisite.keys & REQUISITE_TYPES).first || ('card' if operation.payout_requisite.key?('card_number'))
    end

    # Реквизиты на платформе: вложенные (payout_requisite['sbp'] = {…}) или плоские (payout_requisite['card_number']).
    def requisite_for(operation, requisite_type)
      operation.payout_requisite.fetch(requisite_type) { operation.payout_requisite }
    end

    def build_payout_payload(operation, requisite_type)
      deep_compact(
        {
          merchant_id: credentials.fetch('merchant_id'),
          reference: operation.id.to_s,
          amount: format('%.2f', operation.amount),
          currency: operation.currency,
          description: operation.description || "Payout #{operation.id}",
          callback_url: callback_url,
          destination: build_recipient(operation, requisite_type)
        }
      )
    end

    # Убирает nil, пустые Hash/Array и объекты из одних nil (поля без источника — TODO выше).
    def deep_compact(value)
      case value
      when Hash then value.transform_values { |v| deep_compact(v) }.reject { |_k, v| v.nil? || v == {} || v == [] }
      when Array then value.map { |v| deep_compact(v) }.compact
      else value
      end
    end

    def build_recipient(operation, requisite_type)
      requisite = requisite_for(operation, requisite_type)
      {
        card: {
          pan: requisite['card_number'],
          holder: requisite['holder'],
          expiry: nil, # TODO(forge): map 'destination.card.expiry' (see overrides.yml)
        }
      }
    end

    def parse_create_response(operation, response)
      unless SUCCESS_STATUSES.include?(response.status)
        return failure(http_symbol(response.status), "provider.#{error_code_for(response)}",
                       provider_code: response.body.dig('errors', 0, 'code'), message: response.body.dig('errors', 0, 'message'))
      end

      operations.update(operation.id, provider_operation_key: response.body.dig('data', 'transfer_id'))
      apply_status(operation, response.body.dig('data', 'state'))
    end

    # Успешный ответ без распознаваемого статуса (нет поля или значение вне STATUS_MAP) → in_progress:
    # операция создана, итог придёт через fetch_status / webhook. unknown_provider_status — только для fetch_status.
    def apply_status(operation, provider_status, strict: false)
      status = STATUS_MAP[provider_status.to_s]
      if status.nil?
        return failure(:unprocessable_entity, 'unknown_provider_status', provider_status: provider_status) if strict

        status = 'in_progress'
      end

      transition(operation, status, provider_status: provider_status)
    end

    def error_code_for(response)
      ERROR_MAP.fetch(response.status) { response.body.dig('errors', 0, 'code') || 'unknown_error' }
    end

    # HMAC-SHA512 over the raw request body, base64-encoded (payload assumed: not stated in the spec).
    def verify_signature!(raw_body, headers)
      given = header_value(headers, SIGNATURE_HEADER)
      expected = Base64.strict_encode64(OpenSSL::HMAC.digest('SHA512', credentials.fetch('callback_secret'), raw_body))
      raise Provider::SignatureError, "invalid #{SIGNATURE_HEADER}" unless secure_compare(given, expected)
    end
  end
end
