# frozen_string_literal: true

# Generated by forge 1.0.0 from SwiftPay Outbound Payments 3.0.1 (swiftpay.json).
# Optional helpers for endpoints found in the spec but outside the Provider::BaseService contract.
# Kept out of SwiftpayService on purpose: the service exposes only the four contract methods.

require_relative 'swiftpay_service'

module Provider
  class SwiftpayExtras < SwiftpayService
    def cancel_request(operation)
      response = client.delete("#{BASE_URL}/v1/payments/outbound/#{operation.provider_operation_id}", headers: auth_headers)
      return apply_status(operation, response.body['status']) if response.status == 200

      failure(http_symbol(response.status), "provider.#{error_code_for(response)}")
    end

    def fetch_balance
      response = client.get("#{BASE_URL}/v1/accounts/balance", headers: auth_headers)
      return failure(http_symbol(response.status), "provider.#{error_code_for(response)}") unless response.status == 200

      success(available: response.body['available'], reserved: response.body['reserved'])
    end
  end
end
