# frozen_string_literal: true

# Generated by forge 1.0.0 for SwiftpayService. Fixtures: fixtures.json (same directory).
require_relative 'generated_spec_helper'
require_relative 'swiftpay_service'

RSpec.describe Provider::SwiftpayService do
  subject(:service) { described_class.new(provider: build_record('swiftpay'), operations: operations) }

  let(:operations) { Provider::MemoryOperations.new }
  let(:operation) { build_operation.tap { |op| operations.save(op) } }
  let(:create_fixture) { fixtures['create_request'] }
  let(:provider_id) { dig_path(create_fixture['response_201'], ["payment_id"]) }
  let(:create_url) { "#{described_class::BASE_URL}/v1/payments/outbound" }
  let(:auth_headers) { { 'Authorization' => "Basic #{Base64.strict_encode64('test_login:test_password')}" } }

  describe '#check_conditions' do
    it 'rejects amount below minimum' do
      operation.amount = described_class::MIN_AMOUNT - 0.01
      expect(service.check_conditions(operation, 'create').code).to eq('amount_too_low')
    end

    it 'accepts the fixture operation' do
      expect(service.check_conditions(operation, 'create')).to be_success
    end
  end

  describe '#create_request' do
    it 'creates payout (201)' do
      stub = stub_request(:post, create_url).with(headers: auth_headers) { |req| subset_of?(parse_body(req), create_fixture['request']) }
                                            .to_return(status: 201, body: create_fixture['response_201'].to_json,
                                                       headers: { 'Content-Type' => 'application/json' })
      result = service.create_request(operation, 'create')
      expect(result).to be_success
      expect(stub).to have_been_requested
      expect(operations.find(operation.id).provider_operation_key).to eq(provider_id)
      expect(result.data.dig(:result, :id)).to eq(provider_id) # платформа: provider_operation_key = payload.dig(:result, :id)
      expect(result.data[:status]).to eq(create_fixture['expected_operation_status'])
    end

    it 'maps 422 to provider.validation_error' do
      stub_request(:post, create_url).to_return(status: 422, body: (create_fixture['response_422'] || {}).to_json,
                                                headers: { 'Content-Type' => 'application/json' })
      expect(service.create_request(operation, 'create').code).to eq('provider.validation_error')
    end

    it 'refuses an operation without a known requisite type' do
      operation.payout_requisite = { 'unknown_type' => {} }
      expect(service.create_request(operation, 'create').code).to eq('requisite_missing')
    end

    it 'maps 401 to invalid_credentials' do
      stub_request(:post, create_url).to_return(status: 401, body: '{}')
      expect(service.create_request(operation, 'create').code).to eq('provider.invalid_credentials')
    end

    it 'maps 429 to rate_limit with retry_after' do
      stub_request(:post, create_url).to_return(status: 429, body: '{}', headers: { 'Retry-After' => '60' })
      result = service.create_request(operation, 'create')
      expect(result.code).to eq('provider.rate_limit')
      expect(result.data[:retry_after]).to eq(60)
    end

    it 'maps 5xx to provider.unavailable' do
      stub_request(:post, create_url).to_return(status: 503, body: '{}')
      expect(service.create_request(operation, 'create').code).to eq('provider.unavailable')
    end

    it 'delegates status request_method to fetch_status' do
      operation.provider_operation_key = provider_id
      stub = stub_request(:get, "#{described_class::BASE_URL}/v1/payments/outbound/#{provider_id}")
             .to_return(status: 200, body: fixtures.dig('fetch_status', 'response_200').to_json,
                        headers: { 'Content-Type' => 'application/json' })
      service.create_request(operation, 'status')
      expect(stub).to have_been_requested
    end
  end

  describe '#fetch_status' do
    it 'maps the provider status to approved' do
      operation.provider_operation_key = provider_id
      stub_request(:get, "#{described_class::BASE_URL}/v1/payments/outbound/#{provider_id}")
        .to_return(status: 200, body: fixtures.dig('fetch_status', 'response_200').to_json,
                   headers: { 'Content-Type' => 'application/json' })
      result = service.fetch_status(operation)
      expect(result).to be_success
      expect(result.data[:status]).to eq('approved')
    end
  end

  describe '#process_callback' do
    it 'needs a hand-written signature check' do
      pending 'signature with timestamp is not generated (see report.txt)'
      raise 'implement verify_signature! first'
    end
  end

  describe 'SwiftpayExtras#cancel_request' do
    it 'cancels a pending payout' do
      require_relative 'swiftpay_extras'
      extras = Provider::SwiftpayExtras.new(provider: build_record('swiftpay'), operations: operations)
      operation.provider_operation_key = provider_id
      stub_request(:delete, "#{described_class::BASE_URL}/v1/payments/outbound/#{provider_id}")
        .to_return(status: 200, body: fixtures.dig('cancel', 'response_200').to_json,
                   headers: { 'Content-Type' => 'application/json' })
      expect(extras.cancel_request(operation).data[:status]).to eq('rejected')
    end
  end
end
