# frozen_string_literal: true

# Generated by forge 1.0.0 from API интеграции выплат 1.0 (raiffeisen.yaml).
# Do not edit by hand: regenerate with `bin/forge generate`; adjust decisions in overrides.yml.

require 'json'
require 'openssl'

module Provider
  class RaiffeisenService < BaseService
    BASE_URL = ENV.fetch('RAIFFEISEN_BASE_URL', 'https://test.ecom.raiffeisen.ru/api')
    PRODUCTION_URL = 'https://e-commerce.raiffeisen.ru/api'

    STATUS_MAP = {
      'COMPLETED'            => 'approved',
      'DECLINED'             => 'rejected',
      'IN_PROGRESS'          => 'in_progress',
      'PENDING'              => 'in_progress',
      'WAITING_CONFIRMATION' => 'in_progress'
    }.freeze

    ERROR_MAP = {

    }.freeze

    SUCCESS_STATUSES = [200].freeze
    REQUISITE_TYPES = %w[sbp].freeze
    REQUISITE_TYPE_VALUES = {"sbp"=>"SBP"}.freeze # canonical type → value the provider expects
    STATUS_METHODS = %w[status check].freeze
    SUPPORTED_CURRENCIES = %w[RUB].freeze
    SIGNATURE_HEADER = 'X-Api-Signature-SHA256'

    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?
      return failure(:unprocessable_entity, 'currency_not_supported') unless SUPPORTED_CURRENCIES.include?(operation.currency)
      return failure(:unprocessable_entity, 'currency_too_long') if operation.currency.to_s.length > 3
      return failure(:unprocessable_entity, 'paymentDetails_too_long') if (operation.description || "Payout #{operation.id}").to_s.length > 140
      return failure(:unprocessable_entity, 'phone_too_long') if (requisite_for(operation, requisite_type_for(operation, request_method))['phone']).to_s.length > 15
      return failure(:unprocessable_entity, 'bankAlias_too_long') if (requisite_for(operation, requisite_type_for(operation, request_method))['bank_code']).to_s.length > 255
      return failure(:unprocessable_entity, 'firstName_too_long') if (requisite_for(operation, requisite_type_for(operation, request_method))['first_name']).to_s.length > 140
      return failure(:unprocessable_entity, 'middleName_too_long') if (requisite_for(operation, requisite_type_for(operation, request_method))['middle_name']).to_s.length > 140
      return failure(:unprocessable_entity, 'lastName_too_long') if (requisite_for(operation, requisite_type_for(operation, request_method))['last_name']).to_s.length > 140
      return failure(:unprocessable_entity, 'requisite_missing') unless requisite_type_for(operation, request_method)

      success
    end

    def create_request(operation, request_method = 'create')
      return fetch_status(operation) if STATUS_METHODS.include?(request_method)

      requisite_type = requisite_type_for(operation, request_method)
      return failure(:unprocessable_entity, 'requisite_missing') unless requisite_type

      payload = build_payout_payload(operation, requisite_type)
      response = client.post("#{BASE_URL}/payout/v1/payouts", json: payload, headers: auth_headers)
      parse_create_response(operation, response)
    rescue Provider::RateLimitError => e
      failure(:too_many_requests, 'provider.rate_limit', retry_after: e.retry_after)
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    rescue Provider::ServerError, Provider::ConnectionError => e
      failure(:bad_gateway, 'provider.unavailable', message: e.message)
    end

    def fetch_status(operation)
      response = client.get("#{BASE_URL}/payout/v1/payouts/#{operation.provider_operation_key}", headers: auth_headers)
      return failure(http_symbol(response.status), "provider.#{error_code_for(response)}") unless response.status == 200

      apply_status(operation, response.body.dig('status', 'value'), strict: true)
    rescue Provider::RateLimitError => e
      failure(:too_many_requests, 'provider.rate_limit', retry_after: e.retry_after)
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    rescue Provider::ServerError, Provider::ConnectionError => e
      failure(:bad_gateway, 'provider.unavailable', message: e.message)
    end

    def process_callback(payload, raw_body: nil, headers: {})
      verify_signature!(raw_body || JSON.generate(payload), headers)
      internal_status = STATUS_MAP[payload.dig('payout', 'status')]
      return failure(:unprocessable_entity, 'unknown_provider_status', status: payload.dig('payout', 'status')) unless internal_status

      case internal_status
      when 'approved' then approve_operation(payload.dig('payout', 'id'))
      when 'rejected' then reject_operation(payload.dig('payout', 'id'))
      else mark_in_progress(payload.dig('payout', 'id'))
      end
    rescue Provider::SignatureError
      failure(:unauthorized, 'invalid_signature')
    end

    private

    def auth_headers
      { 'Authorization' => "Bearer #{credentials.fetch('token')}" }
    end

    def requisite_type_for(operation, request_method)
      return request_method if REQUISITE_TYPES.include?(request_method)

      (operation.payout_requisite.keys & REQUISITE_TYPES).first
    end

    # Реквизиты на платформе: вложенные (payout_requisite['sbp'] = {…}) или плоские (payout_requisite['card_number']).
    def requisite_for(operation, requisite_type)
      operation.payout_requisite.fetch(requisite_type) { operation.payout_requisite }
    end

    def build_payout_payload(operation, requisite_type)
      deep_compact(
        {
          id: operation.id.to_s,
          account: credentials.fetch('account'),
          amount: operation.amount.to_f.round(2),
          currency: operation.currency,
          paymentDetails: operation.description || "Payout #{operation.id}",
          payoutMethod: REQUISITE_TYPE_VALUES.fetch(requisite_type, requisite_type),
          incomeTypeCode: '1',
          payoutParams: build_recipient(operation, requisite_type)
        }
      )
    end

    # Убирает nil, пустые Hash/Array и объекты из одних nil (поля без источника — TODO выше).
    def deep_compact(value)
      case value
      when Hash then value.transform_values { |v| deep_compact(v) }.reject { |_k, v| v.nil? || v == {} || v == [] }
      when Array then value.map { |v| deep_compact(v) }.compact
      else value
      end
    end

    def build_recipient(operation, requisite_type)
      requisite = requisite_for(operation, requisite_type)
      base = { phone: requisite['phone'], bankAlias: requisite['bank_code'], firstName: requisite['first_name'], middleName: requisite['middle_name'], lastName: requisite['last_name'], inn: requisite['tax_id'] }
      base
    end

    def parse_create_response(operation, response)
      unless SUCCESS_STATUSES.include?(response.status)
        return failure(http_symbol(response.status), "provider.#{error_code_for(response)}",
                       provider_code: response.body.dig('error', 'code'), message: response.body.dig('error', 'message'))
      end

      operations.update(operation.id, provider_operation_key: response.body['id'])
      apply_status(operation, response.body.dig('status', 'value'))
    end

    # Успешный ответ без распознаваемого статуса (нет поля или значение вне STATUS_MAP) → in_progress:
    # операция создана, итог придёт через fetch_status / webhook. unknown_provider_status — только для fetch_status.
    def apply_status(operation, provider_status, strict: false)
      status = STATUS_MAP[provider_status.to_s]
      if status.nil?
        return failure(:unprocessable_entity, 'unknown_provider_status', provider_status: provider_status) if strict

        status = 'in_progress'
      end

      transition(operation, status, provider_status: provider_status)
    end

    def error_code_for(response)
      ERROR_MAP.fetch(response.status) { response.body.dig('error', 'code') || 'unknown_error' }
    end

    # HMAC-SHA256 over the concatenated fields, hex-encoded.
    def verify_signature!(raw_body, headers)
      given = header_value(headers, SIGNATURE_HEADER)
      expected = OpenSSL::HMAC.hexdigest('SHA256', credentials.fetch('callback_secret'), raw_body)
      raise Provider::SignatureError, "invalid #{SIGNATURE_HEADER}" unless secure_compare(given, expected)
    end
  end
end
