# frozen_string_literal: true

# Generated by forge 1.0.0 from SwiftPay Outbound Payments 3.0.1 (swiftpay.json).
# Do not edit by hand: regenerate with `bin/forge generate`; adjust decisions in overrides.yml.

require 'base64'
require 'json'
require 'openssl'

module Provider
  class SwiftpayService < BaseService
    BASE_URL = ENV.fetch('SWIFTPAY_BASE_URL', 'https://sandbox.swiftpay.example/api')

    STATUS_MAP = {
      'CREATED'          => 'in_progress',
      'SENT'             => 'in_progress',
      'SETTLED'          => 'approved',
      'REJECTED'         => 'rejected',
      'PENDING_APPROVAL' => 'in_progress',
      'RETURNED'         => 'rejected'
    }.freeze

    ERROR_MAP = {
      400 => 'validation_error',
      401 => 'invalid_credentials',
      404 => 'not_found',
      422 => 'validation_error',
      500 => 'internal_error'
    }.freeze

    SUCCESS_STATUSES = [201, 409].freeze # 409: duplicate by Idempotency-Key returns the payout
    REQUISITE_TYPES = %w[bank_account].freeze
    STATUS_METHODS = %w[status check].freeze
    SUPPORTED_CURRENCIES = %w[EUR USD GBP].freeze
    MIN_AMOUNT = 1 # EUR; schema minimum 1
    SIGNATURE_HEADER = 'Swift-Signature'

    def check_conditions(operation, request_method)
      base_result = super
      return base_result if base_result.failed?
      return failure(:unprocessable_entity, 'amount_too_low') if operation.amount < MIN_AMOUNT
      return failure(:unprocessable_entity, 'currency_not_supported') unless SUPPORTED_CURRENCIES.include?(operation.currency)
      return failure(:unprocessable_entity, 'reference_too_long') if operation.id.to_s.length > 35
      return failure(:unprocessable_entity, 'purpose_too_long') if (operation.description || "Payout #{operation.id}").to_s.length > 140
      return failure(:unprocessable_entity, 'requisite_missing') unless requisite_type_for(operation, request_method)

      iban = requisite_for(operation, 'bank_account')['iban']
      return failure(:unprocessable_entity, 'iban_invalid') if requisite_type_for(operation, request_method) == 'bank_account' && !iban.to_s.match?(/\A[A-Z]{2}\d{2}[A-Z0-9]{11,30}\z/)

      success
    end

    def create_request(operation, request_method = 'create')
      return fetch_status(operation) if STATUS_METHODS.include?(request_method)

      requisite_type = requisite_type_for(operation, request_method)
      return failure(:unprocessable_entity, 'requisite_missing') unless requisite_type

      payload = build_payout_payload(operation, requisite_type)
      response = client.post("#{BASE_URL}/v1/payments/outbound", json: payload,
                                                                 headers: auth_headers.merge(idempotency_headers(operation)))
      parse_create_response(operation, response)
    rescue Provider::RateLimitError => e
      failure(:too_many_requests, 'provider.rate_limit', retry_after: e.retry_after)
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    rescue Provider::ServerError, Provider::ConnectionError => e
      failure(:bad_gateway, 'provider.unavailable', message: e.message)
    end

    def fetch_status(operation)
      response = client.get("#{BASE_URL}/v1/payments/outbound/#{operation.provider_operation_key}", headers: auth_headers)
      return failure(http_symbol(response.status), "provider.#{error_code_for(response)}") unless response.status == 200

      apply_status(operation, response.body['status'], strict: true)
    rescue Provider::RateLimitError => e
      failure(:too_many_requests, 'provider.rate_limit', retry_after: e.retry_after)
    rescue Provider::UnauthorizedError
      failure(:unauthorized, 'provider.invalid_credentials')
    rescue Provider::ServerError, Provider::ConnectionError => e
      failure(:bad_gateway, 'provider.unavailable', message: e.message)
    end

    def process_callback(payload, raw_body: nil, headers: {})
      verify_signature!(raw_body || JSON.generate(payload), headers)
      internal_status = STATUS_MAP[payload.dig('data', 'status')]
      return failure(:unprocessable_entity, 'unknown_provider_status', status: payload.dig('data', 'status')) unless internal_status

      case internal_status
      when 'approved' then approve_operation(payload.dig('data', 'payment_id'))
      when 'rejected' then reject_operation(payload.dig('data', 'payment_id'), payload.dig('data', 'reason', 'code'))
      else mark_in_progress(payload.dig('data', 'payment_id'))
      end
    rescue Provider::SignatureError
      failure(:unauthorized, 'invalid_signature')
    end

    # Endpoints outside the BaseService contract (cancel, balance)
    # are generated as optional helpers in swiftpay_extras.rb (SwiftpayExtras < SwiftpayService).

    private

    def auth_headers
      token = Base64.strict_encode64("#{credentials.fetch('login')}:#{credentials.fetch('password')}")
      { 'Authorization' => "Basic #{token}" }
    end

    def idempotency_headers(operation)
      { 'Idempotency-Key' => operation.idempotency_key }
    end

    def requisite_type_for(operation, request_method)
      return request_method if REQUISITE_TYPES.include?(request_method)

      (operation.payout_requisite.keys & REQUISITE_TYPES).first
    end

    # Реквизиты на платформе: вложенные (payout_requisite['sbp'] = {…}) или плоские (payout_requisite['card_number']).
    def requisite_for(operation, requisite_type)
      operation.payout_requisite.fetch(requisite_type) { operation.payout_requisite }
    end

    def build_payout_payload(operation, requisite_type)
      deep_compact(
        {
          reference: operation.id.to_s,
          amount: operation.amount.to_f.round(2),
          currency: operation.currency,
          purpose: operation.description || "Payout #{operation.id}",
          beneficiary: build_recipient(operation, requisite_type)
        }
      )
    end

    # Убирает nil, пустые Hash/Array и объекты из одних nil (поля без источника — TODO выше).
    def deep_compact(value)
      case value
      when Hash then value.transform_values { |v| deep_compact(v) }.reject { |_k, v| v.nil? || v == {} || v == [] }
      when Array then value.map { |v| deep_compact(v) }.compact
      else value
      end
    end

    def build_recipient(operation, requisite_type)
      requisite = requisite_for(operation, requisite_type)
      {
        name: requisite['holder'],
        iban: requisite['iban'],
        bic: requisite['bic'],
        address: { country: requisite['country'] }.compact
      }
    end

    def parse_create_response(operation, response)
      unless SUCCESS_STATUSES.include?(response.status)
        return failure(http_symbol(response.status), "provider.#{error_code_for(response)}",
                       provider_code: response.body['code'], message: response.body['message'])
      end

      operations.update(operation.id, provider_operation_key: response.body['payment_id'])
      apply_status(operation, response.body['status'])
    end

    # Успешный ответ без распознаваемого статуса (нет поля или значение вне STATUS_MAP) → in_progress:
    # операция создана, итог придёт через fetch_status / webhook. unknown_provider_status — только для fetch_status.
    def apply_status(operation, provider_status, strict: false)
      status = STATUS_MAP[provider_status.to_s]
      if status.nil?
        return failure(:unprocessable_entity, 'unknown_provider_status', provider_status: provider_status) if strict

        status = 'in_progress'
      end

      transition(operation, status, provider_status: provider_status)
    end

    def error_code_for(response)
      ERROR_MAP.fetch(response.status) { response.body['code'] || 'unknown_error' }
    end

    # TODO(forge): Swift-Signature includes a timestamp/nonce; implement per provider docs.
    def verify_signature!(_raw_body, _headers)
      raise NotImplementedError, 'signature scheme with timestamp is not generated (see report.txt)'
    end
  end
end
